### ISSUE TITLE
More documentation, please~

### ISSUE THREAD

**Issue by mcandre** [bitcoin-software/bitclouds.sh#11]
* What is a Social Activity Token?
* Which exchanges sell Social Activity Tokens?
* The bitclouds homepage lists a different set of supported operating system guests compared to the README.

**Comment by bitcoin-software** [comment]
Hello! i don't know what you mean with "social activity token". we don't have any.

bitclouds operates over Bitcoin Lightning Network. You can buy an instance with fraction of bitcoin (satoshis)

Agree with you, i should keep docs more updated.

**Comment by bitcoin-software** [comment]
Join our community chat @ https://t.me/BitClouds
