### ISSUE TITLE
Service status of netbsd

### ISSUE THREAD

**Issue by mco13** [bitcoin-software/bitclouds.sh#12]
I just paid for two instances, but they don't seem to recognize:

```
curl https://bitclouds.sh/status/aludra-5
{
  "status": "unpaid"
}

curl https://bitclouds.sh/status/aladfar-6
{
  "status": "unpaid"
}

**Comment by lirre8** [comment]
Just had a similar issue. I topped up my instance with 10000 sats but balance is not affected

**Comment by bitcoin-software** [comment]
Hello, folks!

I had a problem on server side (firewall tables was overloaded it seems). Now it should work. unfortunately, you must re-create an instance, because old new instances will not recover :(

sorry for long response, i was "out of office"

**Comment by lirre8** [comment]
@bitcoin-software How about the 10000 sats I paid for my instance? Those are gone now? The instance is still up and running :)

**Comment by bitcoin-software** [comment]
Ouh, man, i am sorry for this! Please, send me an invoice for 12k sats here, will do a refund. also, you can join a telegram community group https://t.me/BitClouds so we can chat together

**Comment by bitcoin-software** [comment]
By the way, the problem occurs only for new instances (they will not re-init if initial invoice paid during this outage iirc), the instances which were initialized are still working fine and you can add the balance to them now without problems.
