### ISSUE TITLE
Add Ubuntu (and other) older version releases

### ISSUE THREAD

**Issue by bitcoin-software** [bitcoin-software/bitclouds.sh#3]
Users have demand on older OS versions as well.. bitclouds should offer older OS versions for some specific purposes

**Comment by GlenCooper** [comment]
Personally, I don't see it being beneficial to keep any other versions of OSes beyond the latest major LTS version.  This is thinking of how Ubuntu's versioning works... no idea or care about other flavors.

**Comment by bitcoin-software** [comment]
only latest
